project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
preserve_hierarchy: true

export_languages:
  - de

files:
  - source: /src/content/docs/**/*.mdx
    translation: /src/content/docs/%two_letters_code%/**/%original_file_name%
    ignore:
      - /src/content/docs/de/**/*.mdx

  - source: /src/content/i18n/en.json
    translation: /src/content/i18n/%two_letters_code%.json

  - source: /src/content/includes/*.mdx
    translation: /src/content/includes/%two_letters_code%/%original_file_name%
    ignore:
      - /src/content/includes/de/**/*.mdx
