project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
preserve_hierarchy: true

export_languages:
  - de
  - da
  - fr
  - pt-PT
  - es-ES

files:
  - source: /docs/**/*.mdx
    translation: /docs/%two_letters_code%/**/%original_file_name%
    ignore:
      - /docs/de/**/*.mdx
      - /docs/da/**/*.mdx
      - /docs/fr/**/*.mdx
      - /docs/pt/**/*.mdx
      - /docs/es/**/*.mdx

  - source: /strings/en.json
    translation: /strings/%two_letters_code%.json

  - source: /includes/*.mdx
    translation: /includes/%two_letters_code%/%original_file_name%
    ignore:
      - /includes/de/**/*.mdx
      - /includes/da/**/*.mdx
      - /includes/fr/**/*.mdx
      - /includes/pt/**/*.mdx
      - /includes/es/**/*.mdx
